name: Build grpc aarch64

on:
  workflow_dispatch:

env:
  GRPC_VERSION: v1.53.1
  TAG_VERSION: v1.53.1-2

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y git make cmake libssl-dev openssl

      - name: Install Cross-Compile Support
        uses: cyberjunk/gha-ubuntu-cross@v2
        with:
          arch: arm64

      - name: git clone
        shell: bash
        run: |
            git clone --recurse-submodules --depth 1 --branch ${{env.GRPC_VERSION}} https://github.com/grpc/grpc.git

      - name: build host
        shell: bash
        run: |
          cd grpc
          mkdir build-host
          cd build-host
          cmake -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_SSL_PROVIDER=package ..
          make -j 4
          sudo make install

      - name: build aarch64
        shell: bash
        run: |
          cd grpc
          mkdir build-aarch64
          cd build-aarch64
          
          cat > /tmp/toolchain-aarch64.cmake <<'EOT'
          set(CMAKE_SYSTEM_NAME Linux)
          set(CMAKE_SYSTEM_PROCESSOR aarch64)
          set(CMAKE_STAGING_PREFIX build-aarch64)
          set(CMAKE_C_COMPILER /usr/bin/aarch64-linux-gnu-gcc-10)
          set(CMAKE_CXX_COMPILER /usr/bin/aarch64-linux-gnu-g++-10)
          set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
          set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
          EOT

          cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/toolchain-aarch64.cmake \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=`pwd`/grpc-${GRPC_VERSION}/build-aarch64 \
                ..

          make -j 4 
          make install
          cp -a build-aarch64/* grpc-${GRPC_VERSION}/build-aarch64/

      - name: Release
        run: |
          cd grpc/build-aarch64
          mv grpc-${GRPC_VERSION}/build-aarch64/lib/pkgconfig grpc-${GRPC_VERSION}/build-aarch64/lib/pkgconfig.BUILD_VERSION
          tar -czf grpc-aarch64-${{env.GRPC_VERSION}}.tar.gz grpc-${GRPC_VERSION}
          gh release create "${{env.TAG_VERSION}}" -R Zabrimus/grpc-precompiled  || true
          gh release upload "${{env.TAG_VERSION}}" grpc-aarch64-${{env.GRPC_VERSION}}.tar.gz --clobber -R Zabrimus/grpc-precompiled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
